// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicTacToe.Persistence.Contex;

#nullable disable

namespace TicTacToe.Persistence.Migrations
{
    [DbContext(typeof(GameContex))]
    partial class GameContexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TicTacToe.Domain.GameTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("finished")
                        .HasColumnType("boolean");

                    b.Property<int?>("oneXId")
                        .HasColumnType("integer");

                    b.Property<bool?>("p0")
                        .HasColumnType("boolean");

                    b.Property<bool?>("p1")
                        .HasColumnType("boolean");

                    b.Property<bool?>("p2")
                        .HasColumnType("boolean");

                    b.Property<bool?>("p3")
                        .HasColumnType("boolean");

                    b.Property<bool?>("p4")
                        .HasColumnType("boolean");

                    b.Property<bool?>("p5")
                        .HasColumnType("boolean");

                    b.Property<bool?>("p6")
                        .HasColumnType("boolean");

                    b.Property<bool?>("p7")
                        .HasColumnType("boolean");

                    b.Property<bool?>("p8")
                        .HasColumnType("boolean");

                    b.Property<int?>("twoOId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("oneXId");

                    b.HasIndex("twoOId");

                    b.ToTable("GameTables");
                });

            modelBuilder.Entity("TicTacToe.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TicTacToe.Domain.GameTable", b =>
                {
                    b.HasOne("TicTacToe.Domain.User", "oneX")
                        .WithMany()
                        .HasForeignKey("oneXId");

                    b.HasOne("TicTacToe.Domain.User", "twoO")
                        .WithMany()
                        .HasForeignKey("twoOId");

                    b.Navigation("oneX");

                    b.Navigation("twoO");
                });
#pragma warning restore 612, 618
        }
    }
}
